---
title: Jerome Baking Club
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ambardekarsahil@gmail.com
description: A place to bake some foodstuffs
baseurl: ''
url: http://jeromebaking.com
paginate: 5
theme-dark: false
gems:
- jekyll-paginate
- kramdown
markdown: kramdown
